# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 00:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=100000, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleTemplate',
            fields=[
                ('slug', models.SlugField(allow_unicode=True, max_length=64, primary_key=True, serialize=False)),
                ('fields', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='clé')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Max. 60 | Idéalement au format "Jeunes Démocrates de Corse".', max_length=60, verbose_name='titre')),
                ('description', models.CharField(default='Groupe local représentant les jeunes miltants du Mouvement Démocrate', help_text='Max. 160 | Ex. "Groupe local représentant les jeunes miltants du Mouvement Démocrate"', max_length=160)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_created', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(related_name='sites_that_can_be_edited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='module',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.ModuleTemplate'),
        ),
    ]
