# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='clé')),
                ('name', models.CharField(max_length=60, verbose_name='titre')),
                ('description', models.CharField(max_length=160)),
            ],
        ),
    ]
