# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='data',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(default='Groupe local représentant les jeunes adhérents du Mouvement Démocrate', help_text='Max. 160 caractères.', max_length=160),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='Max. 60 caractères. Idéalement au format "Jeunes Démocrates de Corse".', max_length=60, verbose_name='titre'),
        ),
    ]
