# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(default='Jeunes Démocrates de ...', help_text='Max. 60 | Idéalement au format "Jeunes Démocrates de Corse".', max_length=60, verbose_name='titre'),
        ),
    ]
