# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20171214_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletemplate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
