# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20170928_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(default='Groupe local représentant les jeunes miltants du Mouvement Démocrate', help_text='Max. 160 | Ex. "Groupe local représentant les jeunes miltants du Mouvement Démocrate"', max_length=160),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='Max. 60 | Idéalement au format "Jeunes Démocrates de Corse".', max_length=60, verbose_name='titre'),
        ),
    ]
